/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.6.4/userguide/multi_project_builds.html
 */

rootProject.name = "viginti-builder"

includeBuild("../viginti-core")
includeBuild("../viginti-generator")
includeBuild("../viginti-gradle-plugin")
includeBuild("../viginti-doc")
includeBuild("../viginti-tests")
includeBuild("../viginti-examples")


enableFeaturePreview("VERSION_CATALOGS")

dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("./libs.versions.toml"))
        }
    }
}

